'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Alius_Bos.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property buttonA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonBlack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonBlack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonLeftThumbDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonLeftThumbDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonLeftThumbMedium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonLeftThumbMedium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonLeftThumbUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonLeftThumbUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonRightThumbDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonRightThumbDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonRightThumbUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonRightThumbUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonStart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonStart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonWhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonWhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonX() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonX", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Checked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Checked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property colorBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colorBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property colorBrown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colorBrown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property colorCobalt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colorCobalt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property colorCrimson() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colorCrimson", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property colorCyan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colorCyan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property colorGold() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colorGold", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property colorGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colorGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property colorOlive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colorOlive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property colorOrange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colorOrange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property colorPink() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colorPink", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property colorPurple() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colorPurple", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property colorRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colorRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property colorSage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colorSage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property colorSteel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colorSteel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property colorTan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colorTan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property colorTeal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colorTeal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property colorViolet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colorViolet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property colorWhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colorWhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property customSearchIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("customSearchIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icon_23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icon_23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalAssassin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalAssassin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalBerserker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalBerserker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalBombCarrierKill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalBombCarrierKill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalBombPlanted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalBombPlanted", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalBombReturned() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalBombReturned", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalBombTaken() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalBombTaken", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalBonecracker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalBonecracker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalCarjack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalCarjack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalDoNotEnter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalDoNotEnter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalDoubleKill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalDoubleKill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalFlagCaptured() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalFlagCaptured", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalFlagCarrierKill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalFlagCarrierKill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalFlagReturned() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalFlagReturned", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalFlagTaken() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalFlagTaken", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalKillFrenzy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalKillFrenzy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalKillimanjaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalKillimanjaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalKillingSpree() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalKillingSpree", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalKilltacular() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalKilltacular", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalKilltrocity() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalKilltrocity", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalOddballCarrierKill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalOddballCarrierKill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalOverkill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalOverkill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalRampage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalRampage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalRunningRiot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalRunningRiot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalSniperKill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalSniperKill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalSplatter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalSplatter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalStick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalStick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalTripleKill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalTripleKill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property medalUnknown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalUnknown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property noImagePreview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noImagePreview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalAssssin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalAssssin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalBeatDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalBeatDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalBerserker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalBerserker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalBombCarrierKill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalBombCarrierKill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalBombPlanted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalBombPlanted", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalBombReturned() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalBombReturned", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalBombTaken() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalBombTaken", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalCarjack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalCarjack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalDoNotEnter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalDoNotEnter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalDoubleKill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalDoubleKill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalFlagCaptured() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalFlagCaptured", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalFlagCarrierKill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalFlagCarrierKill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalFlagReturned() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalFlagReturned", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalFlagTaken() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalFlagTaken", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalKillfrenzy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalKillfrenzy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalKillimanjaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalKillimanjaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalKillingSpree() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalKillingSpree", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalKilltacular() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalKilltacular", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalKilltrocity() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalKilltrocity", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalOddballCarrierKill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalOddballCarrierKill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalOverkill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalOverkill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalRampage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalRampage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalRunningRiot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalRunningRiot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalSniperKill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalSniperKill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalSplatter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalSplatter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalStick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalStick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalTripleKill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalTripleKill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallMedalUnknown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallMedalUnknown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property symbolCamera() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("symbolCamera", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property symbolCheck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("symbolCheck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property symbolDownload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("symbolDownload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property symbolFlag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("symbolFlag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property symbolFlat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("symbolFlat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property symbolGuest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("symbolGuest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property symbolLock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("symbolLock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property symbolSmile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("symbolSmile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property symbolStar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("symbolStar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property symbolTongue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("symbolTongue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property symbolWink() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("symbolWink", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property symbolX() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("symbolX", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Unchecked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Unchecked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponBattleRifle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponBattleRifle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponBeamRifle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponBeamRifle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponBomb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponBomb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponBrutePlasmaRifle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponBrutePlasmaRifle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponBruteShot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponBruteShot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponCarbine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponCarbine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponDisintegrator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponDisintegrator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponFlag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponFlag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponFlamethrower() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponFlamethrower", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponFuelRodCannon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponFuelRodCannon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponMagnum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponMagnum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponNeedler() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponNeedler", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponOddball() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponOddball", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponPlasmaPistol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponPlasmaPistol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponPlasmaRifle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponPlasmaRifle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponPrototypePlasmaPistol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponPrototypePlasmaPistol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponRightThumbMedium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponRightThumbMedium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponRocketLauncher() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponRocketLauncher", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponSentinelBeam() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponSentinelBeam", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponSentinelBeamBallContrail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponSentinelBeamBallContrail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponSentinelBeamTriple() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponSentinelBeamTriple", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponSentinelGrenadeLauncher() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponSentinelGrenadeLauncher", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponShotgun() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponShotgun", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponSMG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponSMG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponSMGScope() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponSMGScope", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponSniperRifle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponSniperRifle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weaponSword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weaponSword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
