<?php session_start(); include("functions.php"); ?>
<html>
<head>
<title>Finding Your .SOL</title>
<?php include("style.css"); ?>
</head>
<body>
<b><font size="4">Finding Your .SOL</font></b><br><br>Before you do anything with .SOL files, you should first find the folder which contains yours. To get there, do one of the following: (<font color="Red">Stand-Alone Version</font>, <font color="blue">Online Version</font>)<br> <br> <b><u>Windows XP</u></b><br> <b>1.</b> Copy and Paste this into your navigation bar on Internet Explorer, replacing the ***** with your username:<br> <br> C:\Documents and Settings\*****\Application Data\Macromedia\Flash Player\#SharedObjects<br> <br> Then click the folder that should now be sitting
 in the window, it should be named with random letters and numbers. From here, you click (<font color="Red">localhost</font>, <font color="Blue">www.official-linerider.com</font>)<br> <br> <b>2. </b>Go to the Start Menu and click the following:<br> <br> My Computer &gt; C: &gt; Documents and Settings &gt; ***** &gt; Application Data &gt; Macromedia &gt; Flash Player &gt; #SharedObjects &gt; (Random Numbers and letters, should be only folder in here) &gt; (<font color="Red">localhost</font>, <font color="Blue">www.official-linerider.com</font>)<br> <br> <b><u>Mac</u></b><br> <br> Go to your Macintosh HD folder (hardrive) and search "sharedobjects" (You can also use spotlight). Now open this folder, and there should be another one named with random letters and numbers. Open up this folder and now click (<font color="Red">localhost</font>, <font color="Blue">www.official-linerider.com</font>)<br> <br> <b><u>Linux</u></b><br> <br> Copy and Paste this into your navigation bar,
 replacing the ****** with your username:<br> <br> /home/******/.wine/drive_c/windows/profiles/******/ApplicationData/Macromedia/Flash Player/#SharedObjects/<br> <br> Then click the folder that should now be sitting in the window, it should be named with random letters and numbers. From here, you click:<br> <br> (<font color="Red">localhost</font>, <font color="Blue">www.official-linerider.com</font>) &lt; home &lt; ****** &lt; programs &lt; LineRider_beta.exe<br> <br> After you have found the folder with your .SOL file (which should be named savedLines.SOL), right click it, and select "Create Shortcut". Then drag this shortcut to your desktop, so you can easily get in and out of the folder.<br><br>Now that you have this shortcut, you can open it, and drag and drop your .SOL file that you've downloaded.&nbsp; Make sure to rename it "savedlines.sol", and to rename the old "savedlines.SOL" with something else if you have one.<br>
</body>
</html>
